/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.herbas.ed2.treeproject;

import com.google.gson.Gson;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Nicole
 */
public class Interface extends javax.swing.JFrame {

    private ArbolBinario arbol;
    DefaultListModel aves = new DefaultListModel();
    DefaultListModel ubicacion = new DefaultListModel();
    /** Creates new form Interface */
    public Interface() {
        initComponents();
        treeView.setModel(null);
        aves = new DefaultListModel();
        listAves.setModel(aves);
        ubicacion = new DefaultListModel();
        listRegion.setModel(ubicacion);
    }
    
    private void llenarTreeView() {
        Nodo raiz = arbol.getRaiz();
        DefaultMutableTreeNode raizGrafico = new DefaultMutableTreeNode(raiz.visualizar());
        llenarArbolGrafico(raiz, raizGrafico);
        DefaultTreeModel model = new DefaultTreeModel(raizGrafico);
        treeView.setModel(model);
    }
    
    private void llenarArbolGrafico(Nodo t, DefaultMutableTreeNode tNodo) {
        if (t == null) {
            return;
        } else {
            if (t.getIzquierda() != null) {
                Nodo izquierdo = t.getIzquierda();
                DefaultMutableTreeNode child = new DefaultMutableTreeNode(izquierdo.visualizar());
                tNodo.add(child);
                llenarArbolGrafico(izquierdo, child);
            }
            if (t.getDerecha() != null) {
                Nodo derecho = t.getDerecha();
                DefaultMutableTreeNode child = new DefaultMutableTreeNode(derecho.visualizar());
                tNodo.add(child);
                llenarArbolGrafico(derecho,child);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEspecie = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtRegion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeView = new javax.swing.JTree();
        jLabel4 = new javax.swing.JLabel();
        txtRegionB = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listAves = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        txtEspecieB = new javax.swing.JTextField();
        btnMostrarRegion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listRegion = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        txtEspecieE = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtRegionE = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnGuardar = new javax.swing.JMenuItem();
        mnAbrir = new javax.swing.JMenuItem();
        mnCerrar = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Especie: ");

        jLabel2.setText("Edad: ");

        jLabel3.setText("Región: ");

        btnAgregar.setText("Agregar Ave");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(treeView);

        jLabel4.setText("Región: ");

        btnMostrar.setText("Mostrar Aves");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        listAves.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listAves);

        jLabel5.setText("Especie: ");

        btnMostrarRegion.setText("Mostrar Ubicación");
        btnMostrarRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarRegionActionPerformed(evt);
            }
        });

        listRegion.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listRegion);

        jLabel6.setText("Especie: ");

        btnEliminar.setText("Eliminar Ave");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel7.setText("Region:");

        jMenu1.setText("Opciones");

        mnGuardar.setText("Guardar archivo");
        mnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(mnGuardar);

        mnAbrir.setText("Abrir archivo");
        mnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(mnAbrir);

        mnCerrar.setText("Cerrar archivo");
        mnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(mnCerrar);

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txtEdad)
                                    .addComponent(txtRegion)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtRegionB))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEspecieE)
                                            .addComponent(txtRegionE, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnMostrar)
                                            .addComponent(btnAgregar)
                                            .addComponent(btnEliminar))
                                        .addGap(0, 137, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtEspecieB, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarRegion)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtEspecieE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtRegionE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRegionB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtEspecieB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(btnMostrarRegion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if ("".equals(this.txtEspecie.getText()) 
                || "".equals(this.txtEdad.getText()) || "".equals(this.txtRegion.getText())) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos");
        }
        if (arbol == null) {
            String especie = this.txtEspecie.getText();
            int edad = Integer.parseInt(this.txtEdad.getText());
            String region = this.txtRegion.getText();
            if (!especie.equals("") && !txtEdad.equals("") && !region.equals("")) {
                arbol = new ArbolBinario();
                arbol.agregarNodo(especie, edad, region);
                this.txtEspecie.setText("");
                this.txtEdad.setText("");
                this.txtRegion.setText("");
            } 
        } else {
            String especie = this.txtEspecie.getText();
            int edad = Integer.parseInt(this.txtEdad.getText());
            String region = this.txtRegion.getText();
            if (!especie.equals("") && !txtEdad.equals("") && !region.equals("")) {
                arbol.agregarNodo(especie, edad, region);
                this.txtEspecie.setText("");
                this.txtEdad.setText("");
                this.txtRegion.setText("");
            }
        }
        llenarTreeView();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        aves.removeAllElements();
        if ("".equals(this.txtRegionB.getText())) {
            JOptionPane.showMessageDialog(null, "Ingrese la región");
        } else {
            String region = this.txtRegionB.getText();
            List<String> especies = arbol.mostrarAvesPorRegion(region);
            for (int i = 0; i < especies.size(); i++) {
                aves.addElement(especies.get(i));
            }
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void mnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGuardarActionPerformed
        JFileChooser chooser = new JFileChooser();
        int opcion = chooser.showSaveDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File archivoGuardar = chooser.getSelectedFile();
            String ruta = archivoGuardar.getAbsolutePath();
            Gson gson = new Gson();
            String arbolSerializado = gson.toJson(arbol);
            try {
                FileWriter writter = new FileWriter(ruta);
                writter.write(arbolSerializado);
                writter.flush();
                writter.close();
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnGuardarActionPerformed

    private void mnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbrirActionPerformed
        JFileChooser chooser = new JFileChooser();
        int opcion = chooser.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File archivoALeer = chooser.getSelectedFile();
            String data = "";
            try {
                Scanner reader = new Scanner(archivoALeer);
                while (reader.hasNextLine()) {
                    data = data + reader.nextLine();
                }
                Gson gson = new Gson();
                arbol = gson.fromJson(data, ArbolBinario.class);
                llenarTreeView();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_mnAbrirActionPerformed

    private void mnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCerrarActionPerformed
        this.treeView.setModel(null);
    }//GEN-LAST:event_mnCerrarActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_mnSalirActionPerformed

    private void btnMostrarRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarRegionActionPerformed
        ubicacion.removeAllElements();
        if ("".equals(this.txtEspecieB.getText())) {
            JOptionPane.showMessageDialog(null, "Ingrese la especie");
        } else {
            String especie = this.txtEspecieB.getText();
            List<String> regiones = arbol.mostrarUbicacionAves(especie);
            for (int i = 0; i < regiones.size(); i++) {
                ubicacion.addElement(regiones.get(i));
            }
        }
    }//GEN-LAST:event_btnMostrarRegionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if ("".equals(this.txtEspecieE.getText()) && "".equals(this.txtRegionE.getText())) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos");
        } else {
            String especie = this.txtEspecieE.getText();
            String region = this.txtRegionE.getText();
            if (arbol.buscar(especie) == null) {
                JOptionPane.showMessageDialog(null, "No se puede eliminar porque no existe en el árbol");
            } else {
                arbol.eliminar(especie,region);
                treeView.setModel(null);
                this.txtEspecieE.setText("");
                this.txtRegionE.setText("");
            }
        }
        llenarTreeView();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnMostrarRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listAves;
    private javax.swing.JList<String> listRegion;
    private javax.swing.JMenuItem mnAbrir;
    private javax.swing.JMenuItem mnCerrar;
    private javax.swing.JMenuItem mnGuardar;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JTree treeView;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtEspecieB;
    private javax.swing.JTextField txtEspecieE;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtRegionB;
    private javax.swing.JTextField txtRegionE;
    // End of variables declaration//GEN-END:variables

}
